### ISSUE TITLE
Redis deprected message

### ISSUE THREAD

**Issue by cfgv** [ejfinneran/ratelimit#42]
I got the following message, also I see you do it the fix, but I see that you did the fix, but no release of this was released or for some reason this did not stay in last version

```
`Redis.current` is deprecated and will be removed in 5.0. (called from: /xxxxx/xxxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graph_attack-2.1.0/lib/graph_attack/rate_limit.rb:53:in `redis_client')
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end
```

Also, I see something fails in CI

<img width="974" alt="Screen Shot 2022-12-06 at 4 51 18 PM" src="https://user-images.githubusercontent.com/6793843/206030972-ced46dd5-3cdd-486c-8ede-c63557799956.png">

**Comment by andreasknoepfle** [comment]
https://rubygems.org/gems/ratelimit/versions/1.0.4
