### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by oehlschl** [ejfinneran/ratelimit#43]
Per https://github.com/ejfinneran/ratelimit/issues/42, please publish a new version of this gem. 

https://github.com/ejfinneran/ratelimit/compare/v1.0.2...master

Thanks in advance!

**Comment by andreasknoepfle** [comment]
https://rubygems.org/gems/ratelimit/versions/1.0.4

**Comment by oehlschl** [comment]
Thank you very much @andreasknoepfle .
